nelmio_api_doc:
  documentation:
    info:
      title: api.avtoclub.uz
      version: 1.0.0
    paths:
      /api/login:
        post:
          tags:
            - Authentication
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    mobile:
                      type: string
                    password:
                      type: string
                  type: object
                  example:
                    mobile: "931234567"
                    password: "123456"
      /api/token/refresh:
        post:
          tags:
            - Authentication
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    refreshToken:
                      type: string
                  type: object
                  example:
                    refreshToken: d4f509e1609878335be6e6cbc85fdaacd717f7215c8592bdd5598a6fa20057222e1051aae1f1e5a2c6453108f6245b589453e65a4420b7dbfa0cfd3087b13910
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    with_annotation: false
