security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user_provider:
      entity:
        class: App\User\Entity\User
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api
      stateless: true
      entry_point: jwt
      provider: app_user_provider
      json_login:
        check_path: /api/login
        username_path: mobile
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~
      refresh_jwt:
        check_path: /api/token/refresh

  access_control:
   - { path: ^/api/login, roles: PUBLIC_ACCESS }
   - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
   - { path: ^/api/user/signup, roles: PUBLIC_ACCESS }
   - { path: ^/api/user/mobile/code/resend, roles: PUBLIC_ACCESS }
   - { path: ^/api/user/mobile/confirm, roles: PUBLIC_ACCESS }
   - { path: ^/api/doc, roles: PUBLIC_ACCESS }
   - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
